/*
✅ XSS Mitigation
The content security policy (CSP) is configured to be strict and environment-aware.
CSP are the modern way to white-list resources and mitigate XSS attacks.
The CSP created is extremely strict making it appropriate for a high-security application.
The below CSP configuration:
- Disallows all by default (default-src 'none')
- Only allows scripts and styles from self and trusted CDNs
- Uses nonces for inline scripts to allow only those generated by the server
- Restricts images, fonts, and connections to self or data URIs
- In production, enforces HTTPS with upgradeInsecureRequests and blocks mixed content

Secure Headers
Additional security headers are set to protect against common vulnerabilities:
- X-Content-Type-Options: nosniff - Prevents MIME type sniffing
- X-XSS-Protection: 1; mode=block - Enables XSS filtering in browsers
- X-Frame-Options: DENY - Prevents clickjacking by disallowing framing
- Referrer-Policy: strict-origin-when-cross-origin - Controls referrer information sent with requests
- Cache-Control, Pragma, Expires - Prevents caching of sensitive data
- Strict-Transport-Security (HSTS) is conditionally applied in production to enforce HTTPS

Rate Limiting
Rate limiting configurations are provided to mitigate brute-force and DDoS attacks:
- General rate limit: 100 requests per 15 minutes per IP
- API-specific rate limit: 10 requests per 15 minutes per IP

Environment Awareness
The configuration adapts based on the environment (development vs production):
- HSTS is disabled in development to prevent SSL issues with self-signed certificates
- CSP does not enforce upgradeInsecureRequests or blockAllMixedContent in development to avoid issues with browsers like Safari

This configuration provides a robust security foundation for the Express application, balancing security needs with development convenience.
*/

export const securityConfig = {
  // CSP Configuration - Environment aware
  csp: {
    useDefaults: false,
    directives: {
      defaultSrc: ["'none'"],
      scriptSrc: ["'self'", "'nonce-{nonce}'", "https://cdn.jsdelivr.net"], // Will be replaced with actual nonce
      styleSrc: ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com", "https://cdnjs.cloudflare.com"],
      styleSrcElem: ["'self'", "'unsafe-inline'", "https://fonts.googleapis.com", "https://cdnjs.cloudflare.com"],
      imgSrc: ["'self'", "data:"],
      fontSrc: ["'self'", "https://fonts.gstatic.com", "https://cdnjs.cloudflare.com", "data:"],
      connectSrc: ["'self'"],
      formAction: ["'self'"],
      frameAncestors: ["'none'"],
      frameSrc: ["'none'"],
      objectSrc: ["'none'"],
      baseUri: ["'self'"],
      manifestSrc: ["'self'"],
      mediaSrc: ["'none'"],
      workerSrc: ["'none'"],
      childSrc: ["'none'"],
      // Only upgrade to HTTPS in production
      ...(process.env.NODE_ENV === 'production' ? { 
        upgradeInsecureRequests: [],
        blockAllMixedContent: []
      } : {
        // In development, don't include blockAllMixedContent or upgradeInsecureRequests
        // to prevent Safari SSL issues
      })
    }
  },

  // Helmet Configuration
  helmet: {
    contentSecurityPolicy: false, // We handle CSP manually
    crossOriginEmbedderPolicy: false,
    hsts: process.env.NODE_ENV === 'production' ? {
      maxAge: 31536000, // 1 year
      includeSubDomains: true,
      preload: true
    } : false // Disable HSTS in development to prevent SSL issues
  },

  // Additional Security Headers
  headers: {
    'X-Content-Type-Options': 'nosniff',
    'X-XSS-Protection': '1; mode=block',
    'X-Frame-Options': 'DENY',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Cache-Control': 'no-store, no-cache, must-revalidate, private',
    'Pragma': 'no-cache',
    'Expires': '0',
    // Explicitly prevent HTTPS upgrade in development
    ...(process.env.NODE_ENV !== 'production' ? {
      'Strict-Transport-Security': 'max-age=0; includeSubDomains'
    } : {})
  },

  // Rate Limiting Configuration
  rateLimit: {
    store: {
      windowMs: 15 * 60 * 1000, // 15 minutes
      max: 100, // limit each IP to 100 requests per windowMs
      message: 'Too many requests from this IP, please try again later.'
    },
    api: {
      windowMs: 15 * 60 * 1000, // 15 minutes
      max: 10, // limit each IP to 10 API requests per windowMs
      message: 'Too many API requests from this IP, please try again later.'
    }
  }
};

//----------------------------------------------End of File----------------------------------------------