name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scan daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint Security Rules
      run: |
        npm install eslint-plugin-security --save-dev
        npx eslint . --config eslint.config.security.js
      continue-on-error: false

    - name: Start Application
      run: |
        NODE_ENV=test npm start &
        sleep 10
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI_TEST }}
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://localhost:3000'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'
        fail_action: true
        allow_issue_writing: false

    - name: Run OWASP ZAP Full Scan (Low Priority)
      uses: zaproxy/action-full-scan@v0.8.0
      with:
        target: 'http://localhost:3000'
        rules_file_name: '.zap/rules-full.tsv'
        cmd_options: '-a'
        fail_action: false  # Don't fail on low priority issues
        allow_issue_writing: true
      continue-on-error: true

    - name: Upload ZAP Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: zap-reports
        path: |
          report_html.html
          report_json.json
          report_md.md

  dependency-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run npm audit
      run: |
        # Fail on high/critical, allow moderate/low
        npm audit --audit-level=high
      continue-on-error: false

    - name: Run npm audit (full report)
      run: |
        npm audit --json > audit-report.json || true
        echo "Full audit report generated"
      continue-on-error: true

    - name: Upload audit report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: npm-audit-report
        path: audit-report.json
